### ISSUE TITLE
Can crash when building

### ISSUE THREAD

**Issue by samhubbard** [Tymski/SceneReference#1]
Because there can be two different assemblies in Unity projects (one for runtime and one for editor) there is an issue in the script.

```
#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.SceneManagement;
#endif
```

All you need to do is wrap the using statements where it is calling for the editor in a pre-processor directive to ensure that it's only compiled if you're in the editor.

**Comment by Tymski** [comment]
The using statements in the script are already wrapped in a #if UNITY_EDITOR directive and successfully compiled in different projects and Unity versions. There can be many different assemblies in Unity projects. There is a .asmdef file in the repository, so when you add the repo as a unity package, a working assembly should be generated automatically.
Can you provide more information about your issue and perhaps a console output of your error?

**Comment by samhubbard** [comment]
Yeah, this is totally my bad. I copied and pasted. Then Rider took care of all of the using statements for me without the preprocessor directives. As soon as I had added them I was able to perform builds again. The error message that I was getting was because I was trying to compile and build Editor code (those using statements).

I'll close this down.
